records/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :records, only: [:index, :new, :show]
  resources :records, expect: [:delete, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

records/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

records/app/models/post.rb
class Post < ApplicationRecord
end

records/app/models/record.rb
class Record < ApplicationRecord
end

records/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

records/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :artist, :string, :year, :integer, :conver_art, :string, :song_count, :integer)
    end
end

records/app/controllers/records_controller.rb
class RecordsController < ApplicationController

def index
  @records = Record.all
  # render :index
end

def show
    @record = Record.find(params[:id])
    render :show #optional
end

def new
    @record = Record.new
    render :new #optional
end

def create
    Record.create(record_params)
    redirect_to('/records')
end

private

  def record_params
    params.require(:record).permit(:title, :artist, :year, :conver_art, :song_count)
  end
end # end of class

records/app/helpers/application_helper.rb
module ApplicationHelper
end

records/app/helpers/posts_helper.rb
module PostsHelper
end

records/app/helpers/records_helper.rb
module RecordsHelper
end

records/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Records</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= link_to "Make a New Record", new_record_path %>     <!-- good -->

<%= yield %>
  </body>
</html>

records/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :integer %>
    <%= f.text_field :integer %>
  </div>

  <div class="field">
    <%= f.label :conver_art %>
    <%= f.text_field :conver_art %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :song_count %>
    <%= f.text_field :song_count %>
  </div>

  <div class="field">
    <%= f.label :integer %>
    <%= f.text_field :integer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

records/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

records/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>String</th>
      <th>Year</th>
      <th>Integer</th>
      <th>Conver art</th>
      <th>String</th>
      <th>Song count</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.artist %></td>
        <td><%= post.string %></td>
        <td><%= post.year %></td>
        <td><%= post.integer %></td>
        <td><%= post.conver_art %></td>
        <td><%= post.string %></td>
        <td><%= post.song_count %></td>
        <td><%= post.integer %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

records/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

records/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @post.artist %>
</p>

<p>
  <strong>String:</strong>
  <%= @post.string %>
</p>

<p>
  <strong>Year:</strong>
  <%= @post.year %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @post.integer %>
</p>

<p>
  <strong>Conver art:</strong>
  <%= @post.conver_art %>
</p>

<p>
  <strong>String:</strong>
  <%= @post.string %>
</p>

<p>
  <strong>Song count:</strong>
  <%= @post.song_count %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @post.integer %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

records/app/views/records/index.html.erb
<h1>Rock 'n Rails! (records#index)</h1>

<% @records.each do |record| %>
  <p>Title: <%= record.title %></p>
  <p>Artist: <%= record.artist %></p>
  <img src="<%= record.conver_art %>">
 <br>
  <!-- anchor tag that links to a show page -->
  <%= link_to "Show page", record_path(record) %>       <!-- good -->
<% end %>

records/app/views/records/new.html.erb
<%= form_for @record do |f| %>
  <span>Title: </span>
  <%= f.text_field :title, required: true %><br>
  <span>Artist: </span>
  <%= f.text_field :artist, required: true %><br>
  <span>Year: </span>
  <%= f.number_field :year, required: true %><br>
  <span>Cover art: </span>
  <%= f.url_field :conver_art %><br>
  <span>Song count: </span>
  <%= f.number_field :song_count, required: true %><br>
  <%= f.submit %>
<% end %>

records/app/views/records/show.html.erb
<h1>Rock 'n Rails! (records#show)</h1>

<img src="<%= @record.conver_art %>">
<h1><%= @record.title %></h1>
<h2>by <%= @record.artist %></h2>
<p>Year: <%= @record.year %></p>
<p>Song Count: <%= @record.song_count %></p>
<%= link_to "Back", records_path %>